import {createRouter,createWebHistory, createWebHashHistory} from 'vue-router'
const routes = [
    {        
        path:'/',
        redirect:'/Home',
        component:()=>import('../components/Pages/MianPage.vue'),
        children:[]
    },
    
    {
        path:'/Home',
        name:'Home',
        component:()=>import('../components/Pages/MianPage.vue')
    },
    {
        path:'/Scenic',
        name:'Scenic',
        component:()=>import('../components/Pages/Scenic.vue')
    },
    {
        path:'/Teams',
        name:'Teams',
        component:()=>import('../components/Pages/Teams.vue')
    },
    {
        path:'/Notes',
        name:'Notes',
        component:()=>import('../components/Pages/Notes.vue')
    },
    {
        path:'/NotesDetail',
        name:'NotesDetail',
        component:()=>import('../components/Pages/NotesDetail.vue')
    },
    {
        path:'/Mall',
        name:'Mall',
        component:()=>import('../components/Pages/Mall.vue')
    },
    {
        path:'/My',
        name:'My',
        component:()=>import('../components/Pages/My.vue')
    },
    {
        path:'/Search',
        name:'Search',
        component:()=>import('../components/Pages/Search.vue')
    },
    {
        path:'/ScenicDetail',
        name:'ScenicDetail',
        component:()=>import('../components/Pages/ScenicDetail.vue')
    },
    {
        path:'/aa',
        name:'aa',
        component:()=>import('../components/Pages/aa.vue')
    },
    {
        path:'/ScenicContent',
        name:'ScenicCOntent',
        component:()=>import('../components/Pages/ScenicContent.vue')
    },
    {
        path:'/MallDetail',
        name:'MallDetail',
        component:()=>import('../components/Pages/MallDetail.vue')
    },
    {
        path:'/AdminCenter',
        name:'AdminCenter',
        redirect:'/AdminCenter/AdminCenterHome',
        meta:{
            keepAlive:true,
            cache: true
        },
        component:()=>import('../components/Pages/AdminCenter.vue'),
        children:[
            {
                path:'AdminCenterHome',
                name:'AdminCenterHome',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterHome.vue')
            },
            {
                path:'AdminCenterCommentManage',
                name:'AdminCenterCommentManage',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterCommentManage.vue')
            },
            {
                path:'AdminCenterExchangeHistory',
                name:'AdminCenterExchangeHistory',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterExchangeHistory.vue')
            },
            {
                path:'AdminCenterOfficialManage',
                name:'AdminCenterOfficialManage',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManage.vue'),
                redirect:'/AdminCenter/AdminCenterOfficialManage/ScenicEdit',
                children:[
                    {
                        path:'ScenicEdit',
                        name:'ScenicEdit',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManageFolder/ScenicEdit.vue')
                    },
                    {
                        path:'NoticeEdit',
                        name:'NoticeEdit',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManageFolder/NoticeEdit.vue')
                    },
                    {
                        path:'GoodsEdit',
                        name:'GoodsEdit',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManageFolder/GoodsEdit.vue')
                    },
                    {
                        path:'SpotEdit',
                        name:'SpotEdit',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManageFolder/SpotEdit.vue')
                    },
                    {
                        path:'ExchangeEdit',
                        name:'ExchangeEdit',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterOfficialManageFolder/ExchangeEdit.vue')
                    },
                    
                ]
            },
            {
                path:'AdminCenterPersonal',
                name:'AdminCenterPersonal',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPersonal.vue')
            },
            {
                path:'AdminCenterPublish',
                name:'AdminCenterPublish',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublish.vue'),
                redirect:'/AdminCenter/AdminCenterPublish/Write',
                children:[
                    {
                        path:'Official',
                        name:'Official',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/Official.vue'),
                        redirect:'/AdminCenter/AdminCenterPublish/Official/Notices',
                        children:[
                            {
                                path:'OfficialGOods',
                                name:'OfficialGOods',
                                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/OfficialFolder/OfficialGoods.vue')       
                            },
                            {
                                path:'Notices',
                                name:'Notices',
                                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/OfficialFolder/Notices.vue')      
                            },
                            {
                                path:'Resource',
                                name:'Resource',
                                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/OfficialFolder/Resource.vue')     
                            },

                        ]
                    },
                    {
                        path:'Video',
                        name:'Video',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/Video.vue')
                    },
                    {
                        path:'Write',
                        name:'Write',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishFolder/Write.vue')
                    }
                ]
            },
            {
                path:'AdminCenterPublishManage',
                name:'AdminCenterPublishManage',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterPublishManage.vue')
            },
            {
                path:'AdminCenterTeamManage',
                name:'AdminCenterTeamManage',
                component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterTeamManage.vue'),
                redirect:'/AdminCenter/AdminCenterTeamManage/TeamContent',
                children:[
                    {
                        path:'TeamContent',
                        name:'TeamContent',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterTeamFolder/TeamContent.vue')
                    },
                    {
                        path:'NoteManager',
                        name:'NoteManager',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterTeamFolder/NoteManager.vue')
                    },
                    {
                        path:'NewsManager',
                        name:'NewsManager',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterTeamFolder/NewsManager.vue')
                    },
                    {
                        path:'MemberManage',
                        name:'MemberManage',
                        component:()=>import('../components/Pages/AdminCenterFolder/AdminCenterTeamFolder/MemberManage.vue')
                    }
                ]
            }
        ]
    },
    {
        path:'/TeamDetail',
        name:'TeamDetail',
        redirect:'/TeamDetail/TeamHome',
        component:()=>import('../components/Pages/TeamDetail.vue'),
        children:[
            {
                path:'TeamHome',
                name:'TeamHome',
                component:()=>import('../components/Pages/TeamDeatilFolder/TeamHome.vue')
            },
            {
                path:'TeamNews',
                name:'TeamNews',
                component:()=>import('../components/Pages/TeamDeatilFolder/TeamNews.vue')
            },
            {
                path:'TeamNotes',
                name:'TeamNotes',
                component:()=>import('../components/Pages/TeamDeatilFolder/TeamNotes.vue')
            },
            {
                path:'TeamWall',
                name:'TeamWall',
                component:()=>import('../components/Pages/TeamDeatilFolder/TeamWall.vue')
            }
            
        ]
    }

]

const router = createRouter({
    history: createWebHashHistory(),
    routes:routes,
   
})
export default router